ActiveSheet : Sheet1
WorkDirectory : C:\Users\JOKOI\GolandProjects\testdata
Length : 5
BitMap : 8191
ParallelNum : 3000
InheritSource :
  - C:\Users\JOKOI\GolandProjects\testdata\report\report[2022-01-02※22-48-05].txt
  - C:\Users\JOKOI\GolandProjects\testdata\report\report[2022-01-02※23-36-06].txt